---
- name: Setup Vprofile Stack
  hosts: locaclhost
  connection: locak
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/output_vars

    - name: Import VPC Variables
      include_vars: vars/vpc_stack

    - name: Import Vprofile setup varaiables
      include_vars: vars/vprostacksetup 

    - name: create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into bastion-key.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: ./loginkey_vpro.pem
        mode: "0600"
      when: vprokey_out.changed