---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: locak
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/output_vars

    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Import Vprofile setup varaiables
      include_vars: vars/vprostacksetup 

    - name: create vprofile ec2 key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: Save private key into bastion-key.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: ./loginkey_vpro.pem
        mode: "0600"
      when: vprokey_out.changed

    - name: create Sec GRP for load balancer
      ec2_group:
        name: vproELB-sg
        description: Allow port 80 from everywhere and all ports within sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out

    - name: create security group for v profile Stack
      ec2_group:
        name: vpro-stack-sg
        description: Allow port 22 from everywhere and all ports within sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"

          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELBSG_out.group_id}}"
      register: vproStackSG_out