- name: Generate artifact & sql files to files directory
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Install jdk, maven, git
      apt:
        state: present
        name: "{{item}}"
        update_cache: yes
      loop:
        - openjdk-8-jdk
        - maven
        - git
    
    - name: Clone the repository
      git:
        repo: "https://github.com/devopshydclub/vprofile-project.git"
        dest: "/Vprofile-repo"
        version: vp-rem
      register: git_status

    - name: mvn install command to build artifact
      command: mvn install
      args:
        chdir: "Vprofile-repo"
      when: git_status.changed
      register: mvn_info

    - name: Copy artifact to files directory
      copy:
        src: "{{item}}"
        dest: "files/ROOT.war"
      with_fileglob: "Vprofile-repo/target/*.war"
    
    - name: Copy sql file to files directory
      copy:
        src: Vprofile-repo/src/main/resources/db_backup.sql
        dest: "files/db_backup.sql"
