---
- name: Deploy SQL file on accounts db
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: copy SQL query to db server
      copy:
        src: "files/db_backup.sql"
        dest: "/tmp/db_backup.sql"
      tags:
        - deploy
    
    - name : restoring db01
      mysql_db:
        name: accounts
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - Restart mysql
      tags:
        - deploy 

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
