- name: set host to ip mapping in /etc/hosts
  hosts: all
  tasks:
    - name: Import Vpc setup vaiables
      include_vars: group_vars/hostsip

    - name: update hosts file for all hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{web01_ip}} web01
          {{app01_ip}} app01
          {{rmq01_ip}} rmq01
          {{mc01_ip}} mc01
          {{db01_ip}} db01
